### ISSUE TITLE
Assets directory not reachable from Auth subdirectories

### ISSUE THREAD

**Issue by letomdev** [anvoz/CodeIgniter-Skeleton#1]
Great job !!!!
A small issue exists when going to the different auth directories as they cannot reach the Bootstrap css. (only if you don't set the full path which is a pain when working with local and remote).
Best regards

**Comment by anvoz** [comment]
Did you mean the issue only occurs if you don't set the full path for `assets_url`?

You can load different config files depending on the `ENVIRONMENT` constant which is defined in `index.php`.
By default, it would be `development` so you can create a separated config file like `application/config/development/assets.php` and set the full path in this file.

**Comment by anvoz** [comment]
Please provide more details if you are still in trouble with this issue.
