### ISSUE TITLE
Where is MY_form_helper.php

### ISSUE THREAD

**Issue by SouthRibbleTech** [anvoz/CodeIgniter-Skeleton#11]
I don't see an addons folder in the code files so the link to install in the addons page does not work.

**Comment by anvoz** [comment]
Hi,

Did you mean this file [MY_form_helper.php](https://github.com/anvoz/CodeIgniter-Skeleton/blob/master/application/modules/addons/data/bs_form_helpers/MY_form_helper.php)? It's actually called `Bootstrap form helpers`. Some addons require this helper and you will have to install it manually.
