### ISSUE TITLE
Multiple dialogs on same page

### ISSUE THREAD

**Issue by jeroencrins** [anvoz/CodeIgniter-Skeleton#17]
Hello.

Is it possible to use multiple dialogs on a same page?
Both dialogs use a different function on the same ajax controller
- products_ajax.php
  - function delete_groups()
  - function delete_segments()

the function for deleting groups is working with the dialog. but deleting segments doesn't work (no dialog).

**Comment by anvoz** [comment]
Can you post some code so I can check? I think it shouldn't be problem with that if you use it correctly. Something like the below should work:

```
function delete_groups()
{
    $this->response->dialog(...);
    $this->response->send();
}

function delete_segments()
{
    $this->response->dialog(...);
    $this->response->send();
}
```

**Comment by jeroencrins** [comment]
The functions in products_ajax controller:

``` php
function delete_group(){

    $id = $this->input->get_post('id');

    if(!empty($id)){
        $this->load->model('m_products_groups');            
        $group = $this->m_products_groups->get_where($id)->row_array();

        if ($this->response->confirm('Productgroep '.$group['title'].' verwijderen', 'Weet u zeker dat u productgroep '.$group['title'].' wilt verwijderen?')){

            //Delete if dialog is confirmed
            $this->m_products_groups->_delete($id);
            $this->response->script('location.reload(true);');

            }
            $this->response->send();

    }

}

function delete_segment(){

    $id = $this->input->get_post('id');

    if(!empty($id)){
        $this->load->model('m_products_segments');          
        $segment = $this->m_products_segments->get_where($id)->row_array();

        if ($this->response->confirm('Productsegment '.$segment['title'].' verwijderen', 'Weet u zeker dat u productsegment '.$segment['title'].' wilt verwijderen?')){

            //Delete if dialog is confirmed
            $this->m_products_segments->_delete($id);
            $this->response->script('location.reload(true);');

            }
            $this->response->send();

    }

}
```

And the HTML links

``` html
<li>
    <a href="" rel="async" ajaxify="<?=base_url()?>products/products_ajax/delete_segment?id=<?=$segment['id']?>">
        <i class="imoon imoon-remove"></i> Segment verwijderen
    </a>
</li>

<a href="" rel="async" ajaxify="<?=base_url()?>products/products_ajax/delete_group?id=<?=$group['id']?>" class="btn btn-danger btn-gradient">
    <span class="imoon imoon-remove"></span>
</a>
```

**Comment by anvoz** [comment]
It looks ok. You may get problem from your model or something else, maybe an undefined index.

> Is it possible to use multiple dialogs on a same page?

The answer is yes. And you should have simpler code to check that, not contain any other logic.

**Comment by jeroencrins** [comment]
Oke thanks for your time and answer. I will keep looking for any bug in my controller or model!

**Comment by jeroencrins** [comment]
Hey Anvoz,

I just have changed te url for deleteting segment in the button for deleting group. When I now click the button it works. So maybe it isn't possible to use multiple dialogs? Or is there anything I did wrong?

Thanks,
Jeroen Crins

**Comment by anvoz** [comment]
Seems like something did wrong. But I can't help based on what you're describing here. Not really clear and enough information for me to check.

Actually our team are using this project on some real productions with all kind of possible cases. Not having problem with multiple dialogs.

If you're talking about overlay dialogs, like 2 dialogs are showing at the same time. It could be a problem because Bootstrap didn't support that.

**Comment by jeroencrins** [comment]
Finally I did find the problem.

The dialog had te be opened when a link in bootstrap dropdown was clicked. The skelton script can't see the dropdown link because it's opened after document ready.

Therefor i added 

``` javascript
$('.dropdown-menu').on('click', 'a[rel]', function(e) { 
       // function for the ajaxify link goes in here 
});
```

And now it works :)
