### ISSUE TITLE
What do you think of adding another piece of software 

### ISSUE THREAD

**Issue by buoncri** [anvoz/CodeIgniter-Skeleton#2]
Hi, today I find your project that is something i thought to do in past and that is really usefoul, especially if it can integrate grocery-crud too.

What do you think about ?

P.S.
thanks in advice.

**Comment by anvoz** [comment]
Hi, thanks for your suggestion.

There are a lot of stuffs like CRUD and ORM for CodeIgniter. IMO, most of them are very good but none of them is really outstanding. Currently I am trying [CI Base Model](https://github.com/jamierumbelow/codeigniter-base-model) for my latest project. It is helpful but not really necessary. The choice depends on your taste and on specific project. So I have decided not to include any more stuffs like CRUD and ORM in CodeIgniter Skeleton by default.

Please also note that CIS has included Ion Auth library which is already have a built-in model for it to work. If you add a new CRUD, you may have to modify the Ion Auth's model.

Thanks.
