### ISSUE TITLE
integrating grocerycrud

### ISSUE THREAD

**Issue by buoncri** [anvoz/CodeIgniter-Skeleton#3]
what do you think about integrate grocerycrud (https://github.com/scoumbourdis/grocery-crud) in your nice skeleton ... as a module or as you think is better. I am not a guru but if you think taht can be intresting, I'll be glad to help you.

**Comment by anvoz** [comment]
Based on what I commented on [this](https://github.com/anvoz/CodeIgniter-Skeleton/issues/2), the short answer is no CRUD (by default).

But if you really want to help, I will let it be an `addon` (not really sure what I should name it yet) for CI Skeleton. The structure is like the below:

```
// Stuffs that not include on CI Skeleton by default
// but they are helpful and require some extra steps to integrate
addons/
    grocery-crud/
        // Stuffs of grocerycrud
        README.md // Installation guide
```

So if someone wants to use grocerycrud, he can copy the files from `addons/grocery-crud` folder to use.

**Comment by martyn62** [comment]
I agree, it shouldn't be part of the core system but I see no reason why it cannot be an addon.

**Comment by buoncri** [comment]
I found someone who show his way to get grocerycrud in hmvc enviroment. http://www.grocerycrud.com/forums/topic/575-ci-modular-extensions-hmvc-grocery-crud/

Now, i'll go to try ...

**Comment by buoncri** [comment]
Using the link of my last comment, i made a module of actual version of GCrud in a clean hmvc enviroment. Next step is move that module to your skeleton.

**Comment by anvoz** [comment]
Cool. I'm waiting for your pull request. Thanks.
